### PR TITLE
feat: add new cli launcher

### PR DESCRIPTION
**Pull request by decave27**
feat: add new cli launcher

modules: inquirer, keyboard

### CODE REVIEW

**Comment by decave27** [comment]
이게바로 입구컷인가요

**Comment by decave27** [comment]
화나네요

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a partial executable path

It's currently on:
[launcher.py:35](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L35)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a partial executable path

It's currently on:
[launcher.py:46](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L46)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a partial executable path

It's currently on:
[launcher.py:13](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L13)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a partial executable path

It's currently on:
[launcher.py:50](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L50)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell

It's currently on:
[launcher.py:46](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L46)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell

It's currently on:
[launcher.py:13](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L13)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell

It's currently on:
[launcher.py:37](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L37)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell

It's currently on:
[launcher.py:50](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L50)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a partial executable path

It's currently on:
[launcher.py:8](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L8)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a partial executable path

It's currently on:
[launcher.py:37](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L37)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell

It's currently on:
[launcher.py:8](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L8)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell

It's currently on:
[launcher.py:35](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L35)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/minibox24/easygamebot) found an issue: No exception type(s) specified

It's currently on:
[launcher.py:36](https://github.com/minibox24/easygamebot/blob/1b8570fd6d674d14df2cad6e79c9e9570b937f3b/launcher.py#L36)
Commit 1b8570fd6d674d14df2cad6e79c9e9570b937f3b

**Comment by minibox24** [comment]
resolve all issues

**Comment by decave27** [comment]
머지나 하세요

**Review by minibox24 — APPROVED** [review]

**Pull request merged**
